POST http://localhost:8080/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "password": "123456",
    "address":"abc",
    "phone":"123456789"
}

###

POST http://localhost:8080/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}

###

POST http://localhost:8080/api/inventory HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJqZWN0IjoidGVzdEB0ZXN0LmNvbSIsImV4cCI6MTY2NjUxOTM0NiwiaWF0IjoxNjY2NDMyOTQ2LCJ1c2VyX2lkIjoyLCJyb2xlIjoiVVNFUiJ9.Q-IDvqjqVuBMcmHghEL2z1s1IBZdYJEYVFYK8bD1pUM

{
  "name":"P2",
  "description":"Product 2",
  "price": 100
}

###

POST http://localhost:8080/api/cart HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJqZWN0IjoidGVzdEB0ZXN0LmNvbSIsImV4cCI6MTY2NjUxOTM0NiwiaWF0IjoxNjY2NDMyOTQ2LCJ1c2VyX2lkIjoyLCJyb2xlIjoiVVNFUiJ9.Q-IDvqjqVuBMcmHghEL2z1s1IBZdYJEYVFYK8bD1pUM

{
  "product_id": 3
}

###

POST http://localhost:8080/api/cart/checkout HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJqZWN0IjoidGVzdEB0ZXN0LmNvbSIsImV4cCI6MTY2NjUxOTM0NiwiaWF0IjoxNjY2NDMyOTQ2LCJ1c2VyX2lkIjoyLCJyb2xlIjoiVVNFUiJ9.Q-IDvqjqVuBMcmHghEL2z1s1IBZdYJEYVFYK8bD1pUM
