version: '3.9'
services:
  orderservdb:
    image: mysql/mysql-server:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    container_name: orderservdb
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_ROOT_HOST: "%"
      RUN_MODE: "Production"
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - orderservdb:/var/lib/mysql

  orderserv:
    image: orderserv
    container_name: orderserv
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - orderservdb
    restart: on-failure
    env_file: ./.env
    command: sh -c "/usr/local/bin/wait && /usr/local/bin/orderserv"
    ports:
      - 8080:80
    expose:
      - 80
    environment:
      - RUN_MODE=Production
      - WAIT_HOSTS=orderservdb:3306, rabbitmq:5672
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    stdin_open: true
    tty: true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  orderservdb:
